import { Menu } from "@/types/Menu";

export const menuData: Menu[] = [
  {
    id: 1,
    title: "Ordinateurs Usagés",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 71,
        title: "Blog Grid with sidebar",
        newTab: false,
        // path: "/blogs/blog-grid-with-sidebar",
        path: "#",
      },
      {
        id: 72,
        title: "Blog Grid",
        newTab: false,
        // path: "/blogs/blog-grid",
        path: "#",
      },
      {
        id: 73,
        title: "Blog details with sidebar",
        newTab: false,
        // path: "/blogs/blog-details-with-sidebar",
        path: "#",
      },
      {
        id: 74,
        title: "Blog details",
        newTab: false,
        // path: "/blogs/blog-details",
        path: "#",
      },
    ],
  },
  {
    id: 2,
    title: "Telephone Usagé",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 71,
        title: "Blog Grid with sidebar",
        newTab: false,
        // path: "/blogs/blog-grid-with-sidebar",
        path: "#",
      },
      {
        id: 72,
        title: "Blog Grid",
        newTab: false,
        // path: "/blogs/blog-grid",
        path: "#",
      },
      {
        id: 73,
        title: "Blog details with sidebar",
        newTab: false,
        // path: "/blogs/blog-details-with-sidebar",
        path: "#",
      },
      {
        id: 74,
        title: "Blog details",
        newTab: false,
        // path: "/blogs/blog-details",
        path: "#",
      },
    ],
  },
  {
    id: 3,
    title: "Pieces",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 71,
        title: "Blog Grid with sidebar",
        newTab: false,
        // path: "/blogs/blog-grid-with-sidebar",
        path: "#",
      },
      {
        id: 72,
        title: "Blog Grid",
        newTab: false,
        // path: "/blogs/blog-grid",
        path: "#",
      },
      {
        id: 73,
        title: "Blog details with sidebar",
        newTab: false,
        // path: "/blogs/blog-details-with-sidebar",
        path: "#",
      },
      {
        id: 74,
        title: "Blog details",
        newTab: false,
        // path: "/blogs/blog-details",
        path: "#",
      },
    ],
  },
  {
    id: 4,
    title: "Gaming",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 71,
        title: "Blog Grid with sidebar",
        newTab: false,
        // path: "/blogs/blog-grid-with-sidebar",
        path: "#",
      },
      {
        id: 72,
        title: "Blog Grid",
        newTab: false,
        // path: "/blogs/blog-grid",
        path: "#",
      },
      {
        id: 73,
        title: "Blog details with sidebar",
        newTab: false,
        // path: "/blogs/blog-details-with-sidebar",
        path: "#",
      },
      {
        id: 74,
        title: "Blog details",
        newTab: false,
        // path: "/blogs/blog-details",
        path: "#",
      },
    ],
  },
  {
    id: 5,
    title: "Reparation",
    newTab: false,
    path: "/",
  },
];
